### ISSUE TITLE
Invoker not removing namespaces from xml without elements

### ISSUE THREAD

**Issue by vale-tech** [rperalta1/OdyAPIGenCSharp#1]
The XmlMarshallingUtil code is not correctly removing namespaces from XElement objects where HasElements is false such as the GetOdysseyReleaseLevel API call. This causes an error on the Odyssey call since the library generated namespaces are included. I was able to add the check to IsNamespaceDeclaration when looping through XElement objects without elements to skip adding back in the namespace attributes. I'm not sure what other calls are impacted. GetOdysseyReleaseLevel just happens to be the one I always use to make sure things are working.

**Comment by rperalta1** [comment]
Could you please send me a sample code where you are using GetOdysseyReleaseLevel API?

Thanks in advance,

**Comment by vale-tech** [comment]
Nothing fancy.
`generated.com.tylertech.xsdbindings.getodysseyreleaselevel.Message message = new generated.com.tylertech.xsdbindings.getodysseyreleaselevel.Message
            {
                NodeID = generated.com.tylertech.xsdbindings.getodysseyreleaselevel.BASEREQUIREDZERO.Item0,
                UserID = "1",
                ReferenceNumber = "hello world",
                Source = "manual.service",                
                MessageType = generated.com.tylertech.xsdbindings.getodysseyreleaselevel.GETODYSSEYRELEASELEVELMESSAGETYPENAME.GetOdysseyReleaseLevel,
            }; `

`generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result reply =
                (generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result)
                odysseyWebServiceInvoker.Invoker(message, "GetOdysseyReleaseLevelResult", typeof(generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result));`

**Comment by valetechsolutions** [comment]
`private static XElement RemoveAllNamespaces(XElement xmlDocument)
        {
            if (!xmlDocument.HasElements)
            {
                XElement xElement = new XElement(xmlDocument.Name.LocalName);
                xElement.Value = xmlDocument.Value;

                foreach (XAttribute attribute in xmlDocument.Attributes())
                    xElement.Add(attribute);

                return xElement;
            }
            XElement buffer = new XElement(xmlDocument.Name.LocalName, xmlDocument.Elements().Select(el => RemoveAllNamespaces(el)));
            foreach (XAttribute attribute in xmlDocument.Attributes())
            {
                if(attribute.IsNamespaceDeclaration){
                    continue;
                }                
                buffer.Add(attribute);
            }
            return buffer;
        }`

First IF statement doesn't actually remove namespaces.

**Comment by rperalta1** [comment]
Hi Vale,
**I will test the C# version with the example you sent me.**
Just a side note:  I tested the Java version and it is working fine. I added the following code to  ExampleAPIs.java, method run:

on run method:
System.out.println("-------------------------------------------------------------------------");
System.out.println("Testing GetOdysseyReleaseLevel -- verifiyingthe release and current patch of an Odyssey server:");
System.out.println("-------------------------------------------------------------------------");
	exampleAPIs.getOdysseyReleaseLevel(odysseyWebServiceInvoker, userId, referenceNumber, source);

And I created a new method that call GetOdysseyReleaseLevel API:

private void getOdysseyReleaseLevel(OdysseyWebServiceInvoker odyInvoker, 
			int userID,	String referenceNumber, String source) throws OdysseyWebServiceException {
		
		generated.com.tylertech.xsdbindings.getodysseyreleaselevel.Message message = 
				new generated.com.tylertech.xsdbindings.getodysseyreleaselevel.Message();
		
		message.setUserID(userID);
		message.setReferenceNumber(referenceNumber);
		message.setSource(source);
		message.setNodeID(new BigInteger("0"));
		message.setMessageType(GETODYSSEYRELEASELEVELMESSAGETYPENAME.GET_ODYSSEY_RELEASE_LEVEL);
					
		generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result reply = 
				(generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result) 
				    odyInvoker.invoker(message, "GetOdysseyReleaseLevelResult", generated.com.tylertech.xsdbindings.getodysseyreleaselevelresult.Result.class);
		
		System.out.println("GetOdysseyReleaseLevel release: " + reply.getRelease());
		System.out.println("GetOdysseyReleaseLevel path: " + reply.getPatch());
	}

The results are:
-------------------------------------------------------------------------
Testing GetOdysseyReleaseLevel -- verifiyingthe release and current patch of an Odyssey server:
-------------------------------------------------------------------------
 INFO [example.ExampleAPIs.main()] (OdysseyWebServiceInvoker.java:63) - XML for request is:
<?xml version='1.0' encoding='UTF-8'?><Message MessageType="GetOdysseyReleaseLevel" NodeID="0" ReferenceNumber="
TEST_REFNUM_1234" UserID="4847" Source="TEST_SOURCE"/>
 INFO [example.ExampleAPIs.main()] (OdysseyWebServiceInvoker.java:71) - Odyssey response was: <Result><Release>2
014.3.24</Release><Patch>00</Patch></Result>
GetOdysseyReleaseLevel release: 2014.3.24
GetOdysseyReleaseLevel path: 00

**Comment by vale-tech** [comment]
Thanks for taking a look. I don't know much Java, but I am guessing your NoNamesWriter class is doing things correctly for both types of calls. The C# version doesn't have a single method for cleaning up namespaces.

**Comment by rperalta1** [comment]
Hi,

I added GetOdysseyReleaseLevel API into the ExampleAPIs.cs and also use your solution and updated the XmlMarshallingUtil.cs in master repository.

**Comment by rperalta1** [comment]
I forgot to say thank you for the effort and taking the time to find and fix the bug. 
All the best,
Raul

**Comment by vale-tech** [comment]
My pleasure. Thank you for the library. It dropped right into another project I was working on and saved a ton of time.
